import { ClerkProvider } from '@clerk/nextjs'
import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`scroll-smooth ${inter.className}`}>
        <ClerkProvider>
          <div className="mx-auto container">
            {children}
          </div>
        </ClerkProvider>
      </body>
    </html>
  )
}
